_wandb:
    value:
        cli_version: 0.21.4
        e:
            0nwur2pm57erb05y4bsicrptch48mwed:
                args:
                    - config/train_shakespeare_char.py
                    - --compile=False
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1081101176832"
                        used: "162666856448"
                email: tomzeng200@gmail.com
                executable: /home/tzeng/anaconda3/envs/lm-arch-comparison/bin/python
                git:
                    remote: git@github.com:mtzig/kv_na.git
                gpu: NVIDIA GeForce RTX 5070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      memoryTotal: "17094934528"
                      name: NVIDIA GeForce RTX 5070 Ti
                      uuid: GPU-fbeb9451-43e8-2f9e-c21d-4f1cf0426b6f
                host: TI-100
                memory:
                    total: "16297312256"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/tzeng/repos/kv_na/train.py
                python: CPython 3.10.18
                root: /home/tzeng/repos/kv_na
                startedAt: "2025-09-17T00:57:58.086490Z"
                writerId: 0nwur2pm57erb05y4bsicrptch48mwed
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.18
            "5": 0.21.4
            "12": 0.21.4
            "13": linux-x86_64
always_save_checkpoint:
    value: false
backend:
    value: nccl
batch_size:
    value: 64
beta1:
    value: 0.9
beta2:
    value: 0.99
bias:
    value: false
block_size:
    value: 256
compile:
    value: false
dataset:
    value: shakespeare_char
decay_lr:
    value: true
device:
    value: cuda
dropout:
    value: 0.2
dtype:
    value: bfloat16
eval_interval:
    value: 250
eval_iters:
    value: 200
eval_only:
    value: false
grad_clip:
    value: 1
gradient_accumulation_steps:
    value: 1
init_from:
    value: scratch
learning_rate:
    value: 0.001
log_interval:
    value: 10
lr_decay_iters:
    value: 5000
max_iters:
    value: 5000
min_lr:
    value: 0.0001
n_embd:
    value: 384
n_head:
    value: 6
n_layer:
    value: 6
out_dir:
    value: out-shakespeare-char
wandb_log:
    value: true
wandb_project:
    value: shakespeare-char
wandb_run_name:
    value: mini-gpt-testslow
warmup_iters:
    value: 100
weight_decay:
    value: 0.1
